### PR TITLE
Jekyll version

### PR DESCRIPTION
**Pull request by lalomartins**
Ok, as far as I can see the Jekyll version now does everything Master does. Please take a look and give me your feedback.

To compare the homepage, you can run jekyll with no arguments (current date), and then with `jekyll --time=2013-01-30` which should make Regular the “next meetup”. (Actually if you're looking at it Friday or later, there will be **no** next meetup, so use `--time=2013-02-28` to get Apps back.)

Important: I haven't tested this on Github Pages to see whether I went too plugin-happy and did something they won't support.

### CODE REVIEW

**Comment by rmehner** [comment]
This is really fucking awesome, thank you for your work. Will look into it next week, pretty much swamped with other work this week.

**Comment by lalomartins** [comment]
I'll obviously remain available for fixes as well as some new features we discussed, like the past meetup archives. Not too thrilled about the Ruby programming and the hacky nature of Jekyll :smiley_cat: but it was a fun learning experience.

**Comment by localheinz** [comment]
@lalomartins @rmehner 

I have started to convert the current BerlinJS site using Jekyll, as you can see [here](https://github.com/berlinjs/berlinjs.org/pull/88). An archive has already been added there. 

Not so sure, though - since _this_ repository hasn't been touched in a while - whether I should go about and work on it, that is:
- [ ] add archive that's already present in [`berlinjs/berlinjs.org`](https://github.com/berlinjs/berlinjs.org)
- [ ] use Jekyll's data features
- [ ] and whatnot

Comments?

**Comment by localheinz** [comment]
Looks pretty cool, though!

**Comment by lalomartins** [comment]
Thanks Andreas!

IIRC, the main reason we abandoned this code was that to realize the design as we wanted, I had to use some features of Jekyll that Github Pages don't support. So in the end it wasn't actually usable for the purposes we intended it.

**Comment by rmehner** [comment]
There'll be more work on it. I initially planned to use December for that but got sick in between. The plan is not only to represent the regular BerlinJS meetups, but all the other great stuff that is happening (apps, angular, meteor, ember, node, open tech school & whatnot) while making it easier to participate.  @mbesser & me wanted to do some more design stuff plus finally pushing out the functional website.

So this is definitely not dead :)

**Comment by localheinz** [comment]
@lalomartins

I understand. In the meanwhile, though, some features have been introduced to Jekyll, namely the `data` feature, which is a lot better than having a large `front matter` block.

**Comment by localheinz** [comment]
@rmehner @mbesser 

I believe it will make a lot of sense to wait until you two have finished the design stuff. If you're fine with that, you could create some static stuff, while I could take care of mixing in some Jekyll. Maybe we can use some of the stuff that @lalomartins has already produced.

What do you think?

**Comment by lalomartins** [comment]
less hacks = good

FWIW my code is probably not perfect anyway, since this was my first serious go at Ruby… I'm not offended if huge chunks (or all) of it are thrown out.

**Comment by localheinz** [comment]
@lalomartins :+1:

**Pull request closed without merging**
